import React from 'react'

function Youtubevideocard() {
  return (
   <>
   
   <iframe style={{width:"400px"}} height="315"  className='mt-4' src="https://www.youtube.com/embed/8Cf1t4nRtaM?si=iZZ4EFwAmtGa9GEM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
   <iframe style={{width:"400px"}} height="315"  className='mt-4' src="https://www.youtube.com/embed/wOGqlVqyvCM?si=vrM7dBI57_GY2KI_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
   <iframe style={{width:"400px"}} height="315" className='mt-4' src="https://www.youtube.com/embed/1zCfALU-PFY?si=wjaAUvhEyd9lSZrw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
   <iframe style={{width:"400px"}} className='mt-4'  height="315" src="https://www.youtube.com/embed/ZIXVPKy09uU?si=AzKiuFQ2aG5uJclq" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
   <iframe style={{width:"400px"}} className='mt-4' height="315" src="https://www.youtube.com/embed/Jn7iSaCxmGQ?si=n9hmoWr9ZCzRUr-N" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
   <iframe style={{width:"400px"}} className='mt-4'  height="315" src="https://www.youtube.com/embed/2B6_lv6Qnps?si=M8E88xhW7KQvq--r" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
   <iframe style={{width:"400px"}} className='mt-4'  height="315" src="https://www.youtube.com/embed/UOTPDeMgkTI?si=60p3jwxzsEsEGBRa" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
   <iframe style={{width:"400px"}} className='mt-4'  height="315" src="https://www.youtube.com/embed/1I9ADpXbD6c?si=SvRDyUtvekkGt1wI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
   <iframe style={{width:"400px"}} className='mt-4'  height="315" src="https://www.youtube.com/embed/YuNLNeIorJw?si=w7I2GiID0E_rJQiH" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
   <iframe style={{width:"400px"}} className='mt-4'  height="315" src="https://www.youtube.com/embed/QkCa--fyGjA?si=_-5kPMD6fDJY5LDM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
   <iframe style={{width:"400px"}} className='mt-4'  height="315" src="https://www.youtube.com/embed/Wxy_M602q8I?si=MZznVA5fJWvh5Ob5" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
   <iframe style={{width:"400px"}} className='mt-4'  height="315" src="https://www.youtube.com/embed/7qWnakYMQDM?si=8mjlhREpsG0uGz50" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
   </>
  )
}

export default Youtubevideocard